[package]
name = "rs-qq"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
rand = "0.8.4"
chrono = "0.4"
openssl = "0.10.36"
md5 = "0.7.0"
byteorder = "1.4"
generic-array = "0.14"
flate2 = { version = "1.0.17", features = ["zlib"], default-features = false }
